version: 2.1

parameters:
  environment:
    type: string
    default: dev

orbs:
  circleci-terraform-orb:
    orbs:
      terraform: circleci/terraform@3.1.0
    jobs:
      tfplan:
        executor:
          name: terraform/default
          resource_class: joeypiccola/home
        parameters:
          environment:
            description: The environment to use for tf vars and which to run a plan against.
            type: string
        steps:
          - checkout
          - terraform/init:
              path: ./terraform
          - terraform/plan:
              path: ./terraform
              var_file: ./<< parameters.environment >>/terraform.tfvars

workflows:
  main:
    jobs:
      - circleci-terraform-orb/tfplan:
          environment: << pipeline.parameters.environment >>


# jobs:
#   say-hello:
#     docker:
#       - image: cimg/base:stable
#     resource_class: joeypiccola/home
