version: 2.1

parameters:
  environment:
    type: string
    default: dev

orbs:
  circleci-terraform-orb:
    executors:
      default:
        docker:
          - image: hashicorp/terraform:1.1.7
        resource_class: joeypiccola/home
    commands:
      init:
        description: run terraform init
        steps:
          - run:
              working_dir: terraform
              command: |
                terraform init -no-color -input=false
      plan:
        description: run terraform plan
        parameters:
          ci_environment:
            default: dev
            description: |
              The terraform environment to run against
            type: string
        steps:
          - run:
              working_dir: terraform
              command: |
                terraform plan -var-file="../tf-environments/<< parameters.ci_environment >>/terraform.tfvars" -out=tfplan -no-color -input=false
    jobs:
      tfplan:
        executor:
          name: circleci-terraform-orb/default
        parameters:
          environment:
            description: The environment to use for tf vars and which to run a plan against.
            type: string
        steps:
          - checkout
          - init
          - plan:
              ci_environment: << parameters.environment >>

workflows:
  main:
    jobs:
      - circleci-terraform-orb/tfplan:
          environment: << pipeline.parameters.environment >>


# jobs:
#   say-hello:
#     docker:
#       - image: cimg/base:stable
#     resource_class: joeypiccola/home
