# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    resource_class: joeypiccola/home
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-goodbye:
    docker:
      - image: cimg/base:stable
    resource_class: joeypiccola/home
    steps:
      - checkout
      - run:
          name: "Say goodbye"
          command: "echo Goodbye, World!"

workflows:
  version: 2
  terraform:
    jobs:
      - say-hello
      - request-approval:
          type: approval
          requires:
            - say-hello
          filters:
            branches:
              only:
                - main
      - say-goodbye
