version: 2.1

parameters:
  ci_environment:
    type: string
    default: dev
  resource_class:
    type: string
    default: joeypiccola/home
  terraform_version:
    default: "1.1.9"
    type: string

orbs:
  circleci-terraform-orb:
    executors:
      default:
        parameters:
          resource_class:
            default: medium
            type: string
          terraform_version:
            default: "1.1.7"
            type: string
        docker:
          - image: hashicorp/terraform:<< parameters.terraform_version >>
        resource_class: << parameters.resource_class >>
    commands:
      init:
        description: run terraform init
        steps:
          - run:
              working_directory: terraform
              command: |
                terraform init -no-color -input=false
      plan:
        description: run terraform plan
        parameters:
          ci_environment:
            default: dev
            description: |
              The terraform environment to run against
            type: string
        steps:
          - run:
              working_directory: terraform
              command: |
                terraform plan -var-file="../tf-environments/<< parameters.ci_environment >>/terraform.tfvars" -out=tfplan -no-color -input=false
    jobs:
      tfplan:
        executor:
          name: default
          resource-class: << parameters.resource_class >>
        parameters:
          ci_environment:
            description: The environment to use for tf vars and which to run a plan against.
            type: string
          resource_class:
            description: The CircleCI resouce class to by used by the executor.
            type: string
        steps:
          - checkout
          - init
          - plan:
              ci_environment: << parameters.ci_environment >>

workflows:
  main:
    jobs:
      - circleci-terraform-orb/tfplan:
          ci_environment: << pipeline.parameters.ci_environment >>
          resource_class: << pipeline.parameters.resource_class >>


# jobs:
#   say-hello:
#     docker:
#       - image: cimg/base:stable
#     resource_class: joeypiccola/home
