version: 2.1

parameters:
  resource_class:
    default: "joeypiccola/home"
    type: string
  image_tag:
    default: "2.9.1"
    type: string
  image_name:
    default: "mcr.microsoft.com/azure-cli"
    type: string

orbs:
  my_orb:
    executors:
      default:
        parameters:
          resource_class:
            default: medium
            type: string
          image_tag:
            default: "2.9.1"
            type: string
          image_name:
            default: mcr.microsoft.com/azure-cli
            type: string
        docker:
          - image: << parameters.image_name >>:<< parameters.image_tag >>
        resource_class: << parameters.resource_class >>
    commands:
      a:
        description: a desc
        steps:
          - run:
              working_directory: terraform
              command: |
                FAV=dog
                echo $FAV
                echo 'export ANIMAL=$FAV' >> $BASH_ENV
                echo 'export COLOR=red' >> $BASH_ENV
      b:
        description: a desc
        steps:
          - run:
              working_directory: terraform
              command: |
                echo $FAV
                echo $ANIMAL
                echo $COLOR
      c:
        description: a desc
        steps:
          - run:
              working_directory: terraform
              command: |
                echo $ANIMAL
                source $BASH_ENV
                echo $ANIMAL
    jobs:
      my_job_a:
        executor:
          name: default
          image_name: << parameters.image_name >>
          image_tag: << parameters.image_tag >>
          resource_class: << parameters.resource_class >>
        parameters:
          resource_class:
            default: "joeypiccola/home"
            type: string
          image_tag:
            default: "2.9.1"
            type: string
          image_name:
            default: "mcr.microsoft.com/azure-cli"
            type: string
        steps:
          - checkout
          - a
          - b
      my_job_b:
        executor:
          name: default
          image_name: << parameters.image_name >>
          image_tag: << parameters.image_tag >>
          resource_class: << parameters.resource_class >>
        parameters:
          resource_class:
            default: "joeypiccola/home"
            type: string
          image_tag:
            default: "2.9.1"
            type: string
          image_name:
            default: "mcr.microsoft.com/azure-cli"
            type: string
        steps:
          - checkout
          - c
workflows:
  main:
    jobs:
      - my_orb/my_job_a:
          resource_class: small
      # - my_orb/my_job_b:
      #     resource_class: small
