version: 2.1

parameters:
  resource_class:
    default: "joeypiccola/home"
    type: string
  image_tag:
    default: "2.9.1"
    type: string
  image_name:
    default: "mcr.microsoft.com/azure-cli"
    type: string

orbs:
  my_orb:
    executors:
      default:
        parameters:
          resource_class:
            default: small
            type: string
          image_tag:
            # default: "2.9.1"
            type: string
          image_name:
            # default: mcr.microsoft.com/azure-cli
            type: string
        docker:
          - image: << parameters.image_name >>:<< parameters.image_tag >>
        resource_class: << parameters.resource_class >>
    commands:
      a:
        description: a desc
        steps:
          - run:
              # working_directory: terraform
              command: |
                mkdir -p workspace
                FAV=dog
                echo "export ANIMAL=$FAV" >> $BASH_ENV
                echo 'export COLOR=red' >> $BASH_ENV
                echo "FAV: $FAV"
                echo "ANIMAL: $ANIMAL"
                echo "COLOR: $COLOR"
                echo $FAV > workspace/fav
                echo "CLOUD: $cloud"
      b:
        description: a desc
        steps:
          - run:
              # working_directory: terraform
              command: |
                ls workspace
                cat workspace/fav
                echo "FAV: $FAV"
                echo "ANIMAL: $ANIMAL"
                echo "COLOR: $COLOR"
      c:
        description: a desc
        steps:
          - run:
              # working_directory: terraform
              command: |
                FAV=$(cat workspace/fav)
                echo "FAV: $FAV"
                pwd
                ls -la
                ls -la workspace
    jobs:
      my_job_a:
        environment:
          cloud='azure'
        executor:
          name: default
          image_name: << parameters.image_name >>
          image_tag: << parameters.image_tag >>
          resource_class: << parameters.resource_class >>
        parameters:
          resource_class:
            type: string
          image_tag:
            type: string
          image_name:
            type: string
        steps:
          - checkout
          - a
          - b
          - persist_to_workspace:
              root: workspace
              paths:
                - fav
      my_job_b:
        executor:
          name: default
          image_name: << parameters.image_name >>
          image_tag: << parameters.image_tag >>
          resource_class: << parameters.resource_class >>
        parameters:
          resource_class:
            type: string
          image_tag:
            type: string
          image_name:
            type: string
        steps:
          - checkout
          - attach_workspace:
              at: workspace
          - c
workflows:
  main:
    jobs:
      - my_orb/my_job_a:
          resource_class: small
          image_name: "mcr.microsoft.com/azure-cli"
          image_tag: "2.9.1"
      - my_orb/my_job_b:
          resource_class: small
          image_name: "hashicorp/terraform"
          image_tag: "1.2.9"
          requires:
            - my_orb/my_job_a
